### ISSUE TITLE
Can we train the periodic and nonperiodic structures together in the training set ?

### ISSUE THREAD

**Issue by jinfeng-data** [ACEsuit/mace#580] opened 2024-09-03 02:25 UTC
Hi, 
  I train a mace model using the periodic and nonperiodic structures together in the training set. When I use the trained model to perform the md simulations, it can run normally under the nonperiodic boundary conditions. But when I move to the periodic boundary conditions, the md simulation is always not stable, with the temperature rising all the time. I want to know, is it ok that we  train the periodic and nonperiodic structures together in the training set? or do we need to add more periodic structures to the training set ? Thanks in advance.

**Comment by gabor1** [comment] 2024-09-03 07:48
This should definitely not happen, and we have not seen it elsewhere. In order to help you debug, we need to see your training input, the log file of the training, a sample of your data (both periodic and non periodic) and the failing MD. If you don't want to share these publicly here, get in touch by email

**Comment by jinfeng-data** [comment] 2024-09-03 09:46
> This should definitely not happen, and we have not seen it elsewhere. In order to help you debug, we need to see your training input, the log file of the training, a sample of your data (both periodic and non periodic) and the failing MD. If you don't want to share these publicly here, get in touch by email
[protein_run-123.log](https://github.com/user-attachments/files/16846633/protein_run-123.log)
[MDsimulation.pos_0.txt](https://github.com/user-attachments/files/16846729/MDsimulation.pos_0.txt)
[run_train.txt](https://github.com/user-attachments/files/16846730/run_train.txt)
[trainingset_sample.txt](https://github.com/user-attachments/files/16846732/trainingset_sample.txt)

Hi, thanks for your reply. I have attached the necessary files. A mini training set sample is in trainingset_sample.xyz, which contains periodic and nonperiodic structures. The training input is in run_train.sh, the log is in protein_run-123.log, and the failed md output is in MDsimulation.pos_0.xyz. The failed MD was run under NVT ensemble with periodic boundary conditions. However, if I run with nonperiodic boundary conditions (i.e. using same molecular structures but with a super large size box), it can run stably and normally. Thanks for your time, and I am looking forward to your reply.

**Comment by gabor1** [comment] 2024-09-03 13:58
what are you using to run the MD ? bonds are starting to break right from the beginning, the trajectory is complete garbage, it's not a question of "stability". can you upload a trajectory with exactly the same input (cube of water) but with no PBC ?

**Comment by gabor1** [comment] 2024-09-03 14:02
(I don't think this is your problem, but I see that you are not using the latest foundation model - it's called mp0b, it's the latest tagged version in the mace-mp repo, it has pair repulsion built-in, so I would always start from that)

**Comment by gabor1** [comment] 2024-09-03 14:04
as a quick check, can you please run the periodic (and non periodic) md with exactly the same initial conditions as this one, but use the foundation model rather than the one you trained (either the one you started form or the mp0b one I mentioned above)

**Comment by jinfeng-data** [comment] 2024-09-03 14:26
> what are you using to run the MD ? bonds are starting to break right from the beginning, the trajectory is complete garbage, it's not a question of "stability". can you upload a trajectory with exactly the same input (cube of water) but with no PBC ?

[simulation.pos_0.txt](https://github.com/user-attachments/files/16850191/simulation.pos_0.txt)
**A trajectory with exactly the same input but with no PBC has been attached. I run MD by using i-PI program as following,**
#!/bin/bash 
#BSUB -gpu "mode=exclusive_process" 
#BSUB -n 1
#BSUB -q gpu2 
#BSUB -o %J.out 
#BSUB -e %J.err 
#BSUB -J md
#BSUB -R "rusage[ngpus_physical=1]" 

#cuda
export CUDA_HOME=/data/home/xiaohe/yuhaochen/software/cuda-11.8/bin
export LD_LIBRARY_PATH=/data/home/xiaohe/yuhaochen/software/cuda-11.8/lib64
export PATH=$PATH:$LD_LIBRARY_PATH:$CUDA_HOME

source /data/home/xiaohe/jinfeng/i-pi-master/env.sh
source /data/home/xiaohe/jinfeng/soft/mace-venv/bin/activate

HOST=$(hostname)

if [ -e simulation.restart ]; then
  sed -i "s/address>[^<]*</address>$HOST</" simulation.restart
  i-pi simulation.restart  >> log.ipi  &
else
  sed -i "s/address>[^<]*</address>$HOST$HOST</" input.xml
  i-pi input.xml > log.ipi &
fi
sleep 3

sed -i "s/\(host = \"\)[^\"]*/\1$HOST$HOST/" run.py
sleep 3

python run.py > out

**where the run.py is as the following,**

from ase.io import read
from mace.calculators import mace_mp
from ase.calculators.socketio import SocketClient
#from ase.calculators.socketio import SocketServer

# Define atoms object
atoms = read("init.xyz", 0)

# Set ASE calculator #################
macemp = mace_mp(model="../model0_multigpus/protein_stagetwo_compiled.model", device='cuda',default_dtype="float32") # return the default medium ASE calculator equivalent to mace_mp(model="medium")
atoms.calc = macemp

# Create Client
host = "gpu10.idm.hsdedu9.comgpu10.idm.hsdedu9.com"
client = SocketClient(unixsocket=host)
client.run(atoms, use_stress=True)

**Comment by gabor1** [comment] 2024-09-03 14:39
another cross-check that you could do is to simply run it entirely within ASE, using DynamicalSystems. I think the problem is somewhere between the ASE calculator and I-PI

**Comment by jinfeng-data** [comment] 2024-09-03 14:42
> as a quick check, can you please run the periodic (and non periodic) md with exactly the same initial conditions as this one, but use the foundation model rather than the one you trained (either the one you started form or the mp0b one I mentioned above)

I test the periodic md by using the foundation model, and the system also becomes garbage immediately at the beginning, which is like the case of using my trained model.

**Comment by gabor1** [comment] 2024-09-03 15:18
ok, so that suggests that it's not the model (because we know that the foundation model is quite happy to run water boxes), but your setup, likely some confusion between ASE and I-PI. Try the pure ASE dynamics to confirm. I'll ask an I-PI expert to comment too.

**Comment by jinfeng-data** [comment] 2024-09-03 22:54
> Hi, the i-PI developer here. Can you share the input.xml file and the configuration that you are using to initialize the i-PI?

[init.txt](https://github.com/user-attachments/files/16858006/init.txt)
[input.txt](https://github.com/user-attachments/files/16858009/input.txt)

Hi, thanks for your reply, and the input.xml and init.xyz have been attached.

**Comment by venkatkapil24** [comment] 2024-09-03 23:10
can you elaborate "the system also becomes garbage immediately at the beginning"? What property are you studying and by immediately do you mean like the first 10 steps or do you mean more. It would really help to see your simulation.out file with the mace-mp-0 model. In so far for 100 steps I have stable temperature control and no signs of instability.

**Comment by jinfeng-data** [comment] 2024-09-03 23:20
[simulation.pos_0.txt](https://github.com/user-attachments/files/16858629/simulation.pos_0.txt)
[simulation.out.txt](https://github.com/user-attachments/files/16858633/simulation.out.txt)

My simulation.out and the trajectory file have been attached. I want to have stable md simulations.

**Comment by jinfeng-data** [comment] 2024-09-04 01:51
> ok, so that suggests that it's not the model (because we know that the foundation model is quite happy to run water boxes), but your setup, likely some confusion between ASE and I-PI. Try the pure ASE dynamics to confirm. I'll ask an I-PI expert to comment too.

 I use ASE dynamics, and it works. The md run is safe and stable under PBC. So it is the problem of i-PI setting, which lead to the md failure.

**Comment by jinfeng-data** [comment] 2024-09-04 01:54
> can you elaborate "the system also becomes garbage immediately at the beginning"? What property are you studying and by immediately do you mean like the first 10 steps or do you mean more. It would really help to see your simulation.out file with the mace-mp-0 model. In so far for 100 steps I have stable temperature control and no signs of instability.

Can I have your input scripts for md run with i-PI ? I want to check whether my scripts are correct.

**Comment by venkatkapil24** [comment] 2024-09-04 09:21
Hi, I have not been able to reproduce your unstable simulations with MACE-MP-0. My simulations are fine. I am using the same input file as you were but here are the input and output files. 
[run-ase.py.txt](https://github.com/user-attachments/files/16866314/run-ase.py.txt)
[simulation.out.txt](https://github.com/user-attachments/files/16866317/simulation.out.txt)
[input.xml.txt](https://github.com/user-attachments/files/16866318/input.xml.txt)

**Comment by jinfeng-data** [comment] 2024-09-04 13:55
I find it is the problem of my previously installed i-PI program. I reinstall the latest version of i-PI, and now it works. Thank you all !

**Comment by ilyes319** [comment] 2024-09-04 17:13
Ok closing then.

**Closed by ilyes319** 2024-09-04 17:13 UTC
