### ISSUE TITLE
Support for virials and stress

### ISSUE THREAD

**Issue by ilyes319** [ACEsuit/mace#3] opened 2022-06-29 12:07 UTC

**Comment by bernstei** [comment] 2022-07-14 19:29
I'm about to start thinking about running the test - what's the state of per-configuration force/energy(/virial) weights, and/or the documentation for this and other features?

**Comment by davkovacs** [comment] 2022-07-15 07:23
The per configuration type weights are implemented and I believe work as intended. 
The stress and virial are also implemented, but are somewhat untested. If you could run some fits with them it would be great. 
As for documentation of features they are documented somewhat in the ReadMe of the repo and in the argument parser if you pass in `--help`.

**Comment by bernstei** [comment] 2022-07-15 13:18
Thanks - it's going to take a little bit to get set up on an NVIDIA (V100) node, and I'm going on holiday for the next week, but I hope to get this tested soon.

**Comment by bernstei** [comment] 2022-07-15 15:19
I don't see any documentation for per-config weights (unless I defined a separate config type for each config, and give it a config-type weight, which will make for an insanely long command line)

**Comment by davkovacs** [comment] 2022-07-15 16:51
Sorry, you are right. The model has stress implemented, but we have not finished it fully yet (ie. there is no data parsing for example). I think it will be ready by the time you are back at the end of next week.

**Comment by bernstei** [comment] 2022-07-15 17:09
I'm sure it's not _necessary_, in the sense that I can group the configurations and probably get equally good results, but it just happens to not be the way I generated my existing per-config weights.

**Comment by bernstei** [comment] 2022-07-19 14:28
1500 epochs in about 6 hours on a V100, without virials actually active. If you let me know when virial parsing is ready, I'll do a proper run.

**Comment by bernstei** [comment] 2022-07-28 19:45
I'm back at work.  Any progress on the virial-parsing version?

**Comment by JonathanSchmidt1** [comment] 2022-08-25 17:54
Is the stress version ready to be merged into main?
Jonathan (we talked at psik about the multigpu)

**Comment by ilyes319** [comment] 2022-09-02 16:08
Sorry for the delay, stress and virials should be working, currently in the stress_develop branch.
To use it, just add to your parsing file these lines:
`    --loss='stress' \
`
`
   --stress_key='your_stress_key'\
`
For virials, please just replace both by ` virials` . You can also change the loss with `stress_weight`.
If you can give it a try that would be great.

**Comment by bernstei** [comment] 2022-09-02 16:29
Thanks - I'll start testing, although it'll probably be a week or so.

**Comment by JonathanSchmidt1** [comment] 2022-09-05 14:40
Training with energy, forces and stress seems to work for me.

**Comment by bernstei** [comment] 2022-09-12 21:29
Any idea about a reasonable value for `stress_weight`, by the way? (although I can't really test until it's possible to turn off stress on a per-config-type basis). I'm currently using weights of 1.0 for energy and 10.0 for force.

**Comment by ilyes319** [comment] 2022-09-12 21:48
Handling missing data is really a priority. I will try to come up with a good solution this week. For the weights, I think a value of 1.0 for both energy and stress seems reasonable and worked good for me.

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bernstei** [comment] 2022-09-20 19:12
What's the current status? The `stress_develop` branch seems to be gone.

**Comment by ilyes319** [comment] 2022-09-21 10:57
The stress branch is now merged into the develop branch. We are still not supporting the missing virials/stress but that is a more generic issue of handling missing data that we need to solve.

**Comment by bernstei** [comment] 2022-09-21 12:20
Thanks.  I'll switch to that branch while I play with it. I only need to ignore the stress in my nonperiodic configs, so I can add a fake stress to those, and make them into a special config type that has zero weight on the stress.

**Comment by bernstei** [comment] 2022-09-30 21:32
@ilyes319 Now that we have stresses in fitting and missing data, what's the status of the remaining step which is supporting prediction of stresses in the ASE Calculator?

**Comment by bernstei** [comment] 2022-09-30 21:40
Does #24 looks right? I'll try to play with a test.

**Closed** 2022-10-18 17:42 UTC
Labels: enhancement

**Comment by hari-ps** [comment] 2025-08-21 07:23
Sorry to bring this discussion again, but after spending some time browsing through the discussion and (wasting some precious GPU compute hours...), I found that the run_train script does not train on stress even though a stress label is provided. The `loss=stress` needs to be added in your yaml file.

Can this aspect be put up on the docpage here: https://mace-docs.readthedocs.io/en/latest/guide/training.html? 

I feel it would tremendously be useful for folks. Please correct me if I am wrong. @ilyes319
