### ISSUE TITLE
foundation models tutorial fails because model parameters are not there

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/mace#228] opened 2023-11-16 16:55 UTC
The instructions in https://mace-docs.readthedocs.io/en/latest/examples/foundation_models.html are not quite complete. When I try to run the 1st code snippet I get
```
bash-4.4$ python3
Python 3.9.16 (main, Jul  3 2023, 20:07:32) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mace.calculators import mace_mp
>>> from ase import build
>>> 
>>> macemp = mace_mp() # return ASE calculator
Using Materials Project model for MACECalculator, see https://huggingface.co/cyrusyc/mace-universal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cluster2/bernstei/.local/lib/python3.9/site-packages/mace/calculators/foundations_models.py", line 31, in mace_mp
    return MACECalculator(model_path, device=device, default_dtype="float32")
  File "/home/cluster2/bernstei/.local/lib/python3.9/site-packages/mace/calculators/mace.py", line 82, in __init__
    raise ValueError(f"Couldn't find MACE model files: {model_paths}")
ValueError: Couldn't find MACE model files: /home/cluster2/bernstei/.local/lib/python3.9/site-packages/mace/calculators/foundations_models/2023-08-14-mace-universal.model
```

The step where the universal model parameters are downloaded (and how you set the path to them) should be a more explicit part of the instructions.

**Comment by ilyes319** [comment] 2023-11-16 18:01
Did you git clone the repo first? The model should be in the path where you git clone, but the problem is that it is searching for the mace in installed by pip. It would be nice to have solution to that.

**Comment by bernstei** [comment] 2023-11-16 18:30
No, I pip installed from the repo. Should I make a PR to get pip to install the models in the same place as it installs the package itself, and change the default path to there? It might involve moving them around a bit, like I had to do for the script entry points.  If so, should I do it relative to the foundations branch?

**Comment by ilyes319** [comment] 2023-11-20 20:07
This was fixed one recent merges, now option to automatically download the checkpoints.

**Closed by ilyes319** 2023-11-20 20:07 UTC
